#ifndef WEBSERV_HPP
#define WEBSERV_HPP

extern bool running;

#define REQUEST_EVENTS EPOLLIN | EPOLLRDHUP | EPOLLERR 
#define RESPONSE_EVENTS EPOLLIN | EPOLLOUT | EPOLLHUP | EPOLLERR

#define CHUNKED_THRESHOLD 1024 * 1024 // 1 MB

#endif